workflows:
  flutter:
    name: Flutter Build

    environment:
      flutter: stable

    scripts:
      - name: Criar projeto Android
        script: |
          flutter create --platforms=android .

      - name: Verificar pasta Android
        script: |
          ls -la
          test -d android

      - name: Instalar dependências
        script: |
          flutter pub get

      - name: Compilar APK
        script: |
          flutter build apk --release
