name: playlivre
description: PlayLivre V2 - Android music player prototype
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  audio_session: ^0.1.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
